services:
    nuxt:
        image: node:18-alpine
        build: ./frontend
        volumes:
            - ./frontend:/frontend
        working_dir: /frontend
        ports:
            - '${FRONTEND_PORT:-3000}:3000'
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - HOST=0.0.0.0
            - port=53004
        command: sh -c "npm install && npm run dev"

    laravel.test:
        build:
            context: ./backend/vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${BACKEND_PORT:-80}:80'
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
        volumes:
            - './backend:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - mailpit

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: laravel
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './backend/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-ppassword'
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
